export interface UserModel {
    accountBalance: string,
    accountNumber: string,
    createdAt: string,
    education: any,
    email: string,
    guarantor: any,
    id: string,
    lastActiveDate: string,
    orgName: string,
    phoneNumber: string,
    profile: any,
    socials: any,
    userName: string,
}